### PR TITLE
rbp: set DISTRO_VERSION to 2016.06

### PR DESCRIPTION
**Pull request by koenkooi**
Signed-off-by: Koen Kooi <koen.kooi@linaro.org>

### CODE REVIEW

**Comment by koenkooi** [comment]
@ndechesne @fboudra

**Comment by ndechesne** [comment]
why would we set it to 2016.06? i don't understand the 'meaning' of it. to me it is almost as if DISTRO_VERSION should be "2.0+linaro" or something like that, to reflect what it is really, no? I don't think we should change VERSION every 3 months, but everything time we switch from 1 version of OE to the next.

**Comment by koenkooi** [comment]
> Op 22 mrt. 2016 om 12:54 heeft Nicolas Dechesne <notifications@github.com> het volgende geschreven:
> 
> why would we set it to 2016.06? i don't understand the 'meaning' of it. to me it is almost as if DISTRO_VERSION should be "2.0+linaro" or something like that, to reflect what it is really, no? I don't think we should change VERSION every 3 months, but everything time we switch from 1 version of OE to the next.
> 
I used the RPB milestone version, but 2.0+Linaro is fine by me as well

**Comment by koenkooi** [comment]
Updated commit to show '2.0+linaro' and force-pushed to 'distroversion' branch

**Comment by ndechesne** [comment]
looks good to me..

**Comment by koenkooi** [comment]
Hmmm, I can't merge this: "Only those with write access to this repository can merge pull requests."

**Pull request merged**
