### PR TITLE
Update rocko builds to use chromium-X11 v.64 and chromium-ozone-wayland v.65

### PR DESCRIPTION
**Pull request by andrey-konovalov**
chromium-x11 is in fact (but not literally) the same as the recipe in OSSystems/master.

chromium-ozone-wayland is v.65 vs v.64 in OSSystems/master; v.64 has the following issues in weston, which make it barely useful:
1) if I go to youtube.com, and enter some text into the search textbox there, I am getting "Aw Snap" (a chromium thread crashes with translation fault) right at the moment I press "Enter" to start the search;
2) sometimes mouse stops working - like the chromium window lost the focus, so that mouse pointer is always the arrow when moving over the chromium window.

Tested on hikey with rpb-weston-image.
chromium-ozone-wayland_65.0.3315.0.r527534.igalia.1.bb used in this PR was also tested on db410c, but in a different build, rocko based as well.

### CODE REVIEW

**Comment by ndechesne** [comment]
it seems to be that this is a backport. as such meta-backports should be used instead.

**Comment by andrey-konovalov** [comment]
It is not exactly the backport, as the upstream is at chromium-ozone-wayland_64, not 65.
But assuming that the mainline meta-browser will be updated to version 65 (maybe when google releases ver. 65 in March), this is kind of backport.
I can move chromium from meta-rpb/recipes-overlayed/ to meta-backports/meta-browser/recipes-browser/ if other maintainers don't mind.

Should I leave the 2nd commit which updates the packagegroups to use the new chromium package names in meta-rpb, or create the three bbappends under meta-backports/meta-rpb/recipes-samples/packagegroups/ with RDEPENDS_packagegroup-rpb-x11_remove = "chromium" and RDEPENDS_packagegroup-rpb_append = " chromium-x11" etc?

**Comment by ndechesne** [comment]
i think it's backport.. let's see if someone else agrees with me..

if we put it in -backports, then you will need to put the packagegroup there as well. since we want to make sure that meta-rpb (alone) still works.

**Comment by petegriffin** [comment]
Andrey did ask on the Wed OE sync call how best to merge this, and the answer was send it to meta-rpb :(

**Comment by fboudra** [comment]
@ndechesne the chromium wayland isn't a backport and the chromium x11 has some minor changes that aren't upstreamed. I think meta-rpb is a better fit for this change than meta-backport. Hence that's what I suggested to Andrey on this week call.

**Comment by ndechesne** [comment]
@petegriffin sorry that I missed the discussion ;) 
@fboudra well, you say it's not a backports because it's not *yet* merged, right? anyways, if you discussed that already, i am fine. just do as you decided..

**Comment by andrey-konovalov** [comment]
Just in case - here is the meta-backports version of these changes:
https://git.linaro.org/people/andrey.konovalov/meta-backports.git/log/?h=work.rocko
The chromium part (the 1st commit) is the same except for the layer it is added to. The packagegroup changes are implemented differently, as bbappends, to have them in the same meta-backports layer.

**Comment by koenkooi** [comment]
If this change is intended to go upstream, I'd prefer it in meta-backports. If it is not intended for upstream, it won't be a backport. 
I'm fine it it going into meta-rbp, but I do have a slight preference for meta-backports.

**Comment by andrey-konovalov** [comment]
As Igalia was going to update the meta-browser themselves [1], and as this change is mostly taken from Igalia's work, I do not plan to send this change upstream myself. I still expect the upstream meta-browser to be updated to chromium-ozone-wayland version 65, or 66 someday, but it will be something similar to this change, but not exactly it, and the chromium revision will not be the same imo.

[1] https://www.mail-archive.com/openembedded-devel@lists.openembedded.org/msg56815.html

**Comment by andrey-konovalov** [comment]
That said, does it still fit into meta-backports better? If yes, I'll create the change request for meta-backports, and close this pull request.
Thanks!

**Comment by andrey-konovalov** [comment]
Created change requests for meta-backports in gerrit:
https://review.linaro.org/#/c/24116/
https://review.linaro.org/#/c/24117/

**Comment by ndechesne** [comment]
I am ok.

Le mer. 28 févr. 2018 à 08:23, Fathi Boudra <notifications@github.com> a
écrit :

**Pull request merged**
