### PR TITLE
packagegroups: include Chromium and ChromeDriver for X11 tests

### PR DESCRIPTION
**Pull request by mrchapp**

### CODE REVIEW

**Comment by fboudra** [comment]
looks good to me. Any reason to enable chromium only on x11? what about weston images?

**Comment by mrchapp** [comment]
Because ``ERROR: chromium was skipped: X11 is not available``.

**Comment by koenkooi** [comment]
nitpick: s/packagroups/packagegroups/

**Comment by mrchapp** [comment]
Fixed, refreshed.

**Comment by ndechesne** [comment]
chromium for wayland is provided with another recipe, chromium-wayland: https://github.com/OSSystems/meta-browser/blob/master/recipes-browser/chromium/chromium-wayland_53.0.2785.143.bb

I suggest we take this as a separate task.

**Pull request merged**
