### PR TITLE
image recipe samples: use networkmanager instead of connman

### PR DESCRIPTION
**Pull request by vishalbhoj**
tested wifi with nmcli  on hikey and dragonboard-410c

Signed-off-by: Vishal Bhoj <vishal.bhoj@linaro.org>

### CODE REVIEW

**Comment by kuscsik** [comment]
lgtm

**Comment by ndechesne** [comment]
please give me a couple of days to look into that.. we have a lot of WLAN test cases, and I need to check what the impact will be.

what kind of testing was done? Does Eth automatically connect when the USB/Ether is inserted? Have you tried WLAN?

**Comment by vishalbhoj** [comment]
I haven't tested usb ethernet dongle at my end.  I have tested wlan, connecting to my wifi network and did a ping test. The network connected automatically after reboot.

**Comment by ndechesne** [comment]
i tried this patch, and it worked fine. tried both Wlan and Ether (with a USB/Ethernet). 

I am still waiting for feedback about the switch regarding the test cases that already exist, so please hold on a bit more.. 

also, if we switch to networkmanager, I would really want that we add networkmanager-nmtui tool by default. Note that switching to network manager drastically increase the image size.. 


From buildhistory:

-IMAGESIZE = 239352
+IMAGESIZE = 258632

+8387	KiB nss
+4702	KiB networkmanager
+2627	KiB libmozjs
+2106	KiB dhcp-client
+857	KiB bash
-720	KiB connman
+348	KiB polkit
+265	KiB nspr
+263	KiB dnsmasq
-87	KiB connman-client
+35	KiB libndp
+30	KiB networkmanager-locale-en-gb

**Comment by fboudra** [comment]
+1 for nmtui

wrt the size cost, I think we should take a closer look if we can improve the situation with PACKAGECONFIG and also upgrade the recipe to latest release.

**Comment by ndechesne** [comment]
i checked on the tests, and we don't depend on connman. so no issue to switch to networkmanager (assuming you take the feedback above into consideration).

**Pull request merged**
