### PR TITLE
recipe-samples/images: Rename -lava images to -test

### PR DESCRIPTION
**Pull request by alimon**
These images are used for testing and not only in LAVA environment, so
it's better to use -test suffix.

Signed-off-by: Aníbal Limón <anibal.limon@linaro.org>

### CODE REVIEW

**Comment by alimon** [comment]
This commit is also target for jethro, krogoth, morty, pyro and rocko branches, cherry pick works i have those branches in my repo.

**Comment by alimon** [comment]
I updated the CI configuration to point -test images,

https://review.linaro.org/#/c/23500/

**Comment by ndechesne** [comment]
good for me. please make sure we do that in *all* branches and we merge the CI/yaml patch first.

**Comment by ndechesne** [comment]
@fboudra , ok to merge? if you are ok, i can do it. just wanted to make sure you're ok.

**Pull request merged**
