### PR TITLE
Lkft metadata

### PR DESCRIPTION
**Pull request by koenkooi**
Add class to write out SRC_URI for lkft and enable it

### CODE REVIEW

**Comment by ndechesne** [comment]
hmm... what is this? can I get more background info? I am not in favor or that being turned ON by default. why don't we enable that in the jobs when it's needed?

**Comment by fboudra** [comment]
@ndechesne for the background, we need to expose some metadata on the QA reports. For a few recipes, we started by using bitbake -e output but it doesn't scale. buildhistory contains most of the information that we need except SRC_URI. The solution is to introduce lkftmetadata class, which is buildhistory with the additional metadata that we want to expose.

I don't mind to enable it only on LKFT build jobs.

**Comment by fboudra** [comment]
@ndechesne I removed the commit to enable by default in RPB and submitted https://review.linaro.org/#/c/21188/

The PR LGTM and if you don't have any objections, I'm happy to merge as-is.

**Comment by ndechesne** [comment]
i think it would be better to squash all patches together.. sure you can say in the commit that you 'started' from buildhistory, but it doesn't bring anything (except confusion) to the git log to keep all these patches. the code at the end is way different from buildhistory.

can you please try to get that feature into buildhistory upstream? it does not sound too crazy to store SRC_URI in buildhistory. 

also the name is ugly and it has nothing to do with meta-rpb.. but ... i won't fight for that today!

**Comment by fboudra** [comment]
@ndechesne squashed and merged.

wrt upstreaming, Koen told me that it has been removed for security concerns. It was a security leak.

wrt naming, I don't have a strong opinion. Maybe it can be improved with a meaningful name. lkftmetadata isn't self explanatory.

**Comment by koenkooi** [comment]
Yes, logging of SRC_URI has been removed in OE-core, so no chance of it going upstream :(

**Comment by ndechesne** [comment]
ah, right. i remember now the removal of SRC_URI... for the same reason, then it should be disabled in RPB by default (like we did).

**Pull request merged**
