### PR TITLE
create nodejs_%.bbappend to fix build failure with long build directo…

### PR DESCRIPTION
**Pull request by andrey-konovalov**
…ry path

Add the patch:
https://github.com/NeoRaider/node/commit/56342b1d56e4270d1587e2e92f74a88e3802e866.patch
from https://github.com/nodejs/node/issues/9137

Signed-off-by: Andrey Konovalov <andrey.konovalov@linaro.org>

### CODE REVIEW

**Comment by andrey-konovalov** [comment]
This fixes https://github.com/96boards/meta-rpb/issues/158

Please let me know if this fix is needed in branches other than rocko. This patch wouldn't apply as is to e.g. morty.

**Comment by mellowcandle** [comment]
Thanks. I will test it. the problem was in our CI so expect 24/36 hours delay before my verdict.

**Comment by mellowcandle** [comment]
Unfortunately the fix doesn't solve the issue :(

**Comment by ndechesne** [comment]
looks ok to me. do we need it in other branches and master?

**Comment by fboudra** [comment]
I guess we need it in master, please confirm

**Pull request merged**
