### PR TITLE
[morty] Add Chromium to packagegroups

### PR DESCRIPTION
**Pull request by mrchapp**

### CODE REVIEW

**Comment by mrchapp** [comment]
The chromium-wayland* commit can be cherry-picked on master.

**Comment by andrey-konovalov** [comment]
Just wander - is it possible to have a simple way to do a build w/o chromium? Simple == something like adding a line to conf/local.conf. The reason I am asking this is that adding chromium to the image doubles the build time.

**Comment by ndechesne** [comment]
This creates a depency between meta-rpb and -backports which is not really
good.

Instead we could bbappend the image recipes in -backports like i did for
kmscube.



Le ven. 7 juil. 2017 à 18:53, andrey-konovalov <notifications@github.com> a
écrit :

**Comment by mrchapp** [comment]
Please see CL [20566](https://review.linaro.org/20566) and [20567](https://review.linaro.org/20567).

**Comment by mrchapp** [comment]
As discussed in CL [20566](https://review.linaro.org/20566), this pull request stands.

**Pull request merged**
