### PR TITLE
wpe: making wpe generic & buildable on rpb

### PR DESCRIPTION
**Pull request by psivasubramanian**
Removed dependencies which has restricted or commercial license to make it build on rpb

### CODE REVIEW

**Comment by koenkooi** [comment]
No such recipe exists in the default build:
[koen@thinkpad layers]$ find . -name "wpe*.bb"
[koen@thinkpad layers]$ 

Just like with your other PR, why does this need to be in meta-rpb? Where's the link to the review of the patch to fix wpe.bb?

**Comment by psivasubramanian** [comment]
This change is required for compiling wpe on hikey rpb

**Comment by koenkooi** [comment]
That still tells me nothing. What is the issue you're trying to fix (error log!) and where is the upstream wpe recipe located (URL!) and a link to the patch submission to fix it upstream.

**Comment by psivasubramanian** [comment]
I'm trying to disable libprovisioning & commercial gstreamer plugins for compiling wpe
https://github.com/Metrological/meta-metrological/tree/master/recipes-wpe/wpe - link to wpe recipe

**Comment by koenkooi** [comment]
Ok, you answered one out of three:

 - [x] Where is the upstream wpe recipe located (URL!) 

 that leaves:

- [ ] What is the issue you're trying to fix (error log!) 
- [ ] Link to the patch submission to fix it upstream.

But regardless of that, meta-metrological isn't in the rpb manifest, so a bbappend for that layer won't be accepted.

**Comment by psivasubramanian** [comment]
Ok, Thanks.

**Pull request closed without merging**
