### PR TITLE
Fix autorev

### PR DESCRIPTION
**Pull request by ndechesne**
LTP and kselftests have been moved to meta-lkft.

### CODE REVIEW

**Comment by daniel-thompson** [comment]
Does recipes-samples/packagegroups/packagegroup-rpb-tests.bb and recipes-samples/packagegroups/packagegroup-rpb-lkft.bb and the corresponding -test and -lkft images also need to be tidied up? These packages will no longer buildable in pure rpb.

**Comment by ndechesne** [comment]
> Does recipes-samples/packagegroups/packagegroup-rpb-tests.bb and recipes-samples/packagegroups/packagegroup-rpb-lkft.bb and the corresponding -test and -lkft images also need to be tidied up? These packages will no longer buildable in pure rpb.

you are 50% right ;) while ltp recipe was an overlay, which means that there is an existing recipe in oe-core, kselfttests doesn't exist in oe-core.. so any image that includes ltp would build, not not for kselftests... I will update the PRs and remove -the -lkft images.

**Comment by ndechesne** [comment]
PR updated, I added a commit to remove the -lkft image and packagegroup.

@mrchapp , can you please review/ack?

**Comment by fboudra** [comment]
fwiw, ltp is also in meta-backports.

**Pull request merged**
